using PIKATWEAKS2.Models;
namespace PIKATWEAKS2.Services;
public static class TweakCatalog
{
    static Tweak T(string id,string name,string desc,string cat,string cmd,bool rec=false,bool restart=false,bool maintenance=false)=>new(id,name,desc,cat,cmd,rec,restart,maintenance);
    public static IReadOnlyList<Tweak> All { get; } = new List<Tweak>
    {
T("01","Disable transparency","Turns off Windows transparency effects.","Windows",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v EnableTransparency /t REG_DWORD /d 0 /f",true),
T("02","Disable taskbar animations","Disables taskbar animation effects.","Windows",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarAnimations /t REG_DWORD /d 0 /f",true),
T("03","MenuShowDelay = 0","Removes the menu-open delay.","Windows",@"reg add ""HKCU\Control Panel\Desktop"" /v MenuShowDelay /t REG_SZ /d 0 /f",true),
T("04","Show file extensions","Always shows known file extensions in Explorer.","Windows",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v HideFileExt /t REG_DWORD /d 0 /f",true),
T("05","Open Explorer to This PC","Makes Explorer open to This PC.","Windows",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v LaunchTo /t REG_DWORD /d 1 /f",true),
T("06","Disable Aero Peek","Disables Aero Peek.","Windows",@"reg add ""HKCU\Software\Microsoft\Windows\DWM"" /v EnableAeroPeek /t REG_DWORD /d 0 /f"),
T("07","Disable Aero Shake","Disables window shake minimization.","Windows",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v DisallowShaking /t REG_DWORD /d 1 /f"),
T("08","Hide Widgets button","Hides the taskbar Widgets button where supported.","Windows",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarDa /t REG_DWORD /d 0 /f"),
T("09","Disable recent-item tracking","Stops Explorer recent-document tracking.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Start_TrackDocs /t REG_DWORD /d 0 /f",true),
T("10","Disable lock-screen suggestions","Disables lock-screen rotating content suggestions.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v RotatingLockScreenOverlayEnabled /t REG_DWORD /d 0 /f",true),
T("11","Disable notification toasts","Disables Windows notification toasts.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings"" /v NOC_GLOBAL_SETTING_TOASTS_ENABLED /t REG_DWORD /d 0 /f"),
T("12","Disable Start suggestions","Disables Start content suggestions.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-338388Enabled /t REG_DWORD /d 0 /f"),
T("13","Disable Spotlight features","Disables Windows Spotlight feature flags.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v DisableWindowsSpotlightFeatures /t REG_DWORD /d 1 /f"),
T("14","Disable app-launch tracking","Disables Start app-launch tracking.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Start_TrackProgs /t REG_DWORD /d 0 /f"),
T("15","Disable Windows tips","Disables Windows tips content.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-338389Enabled /t REG_DWORD /d 0 /f"),
T("16","Disable feedback prompts","Stops periodic Windows feedback prompts.","Privacy",@"reg add ""HKCU\Software\Microsoft\Siuf\Rules"" /v NumberOfSIUFInPeriod /t REG_DWORD /d 0 /f"),
T("17","Enable Game Mode","Enables automatic Game Mode.","Gaming",@"reg add ""HKCU\Software\Microsoft\GameBar"" /v AutoGameModeEnabled /t REG_DWORD /d 1 /f",true),
T("18","Disable Game DVR","Disables Game DVR recording.","Gaming",@"reg add ""HKCU\System\GameConfigStore"" /v GameDVR_Enabled /t REG_DWORD /d 0 /f",true),
T("19","Disable Game Bar capture","Disables Game Bar capture.","Gaming",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR"" /v AppCaptureEnabled /t REG_DWORD /d 0 /f",true),
T("20","Enable HAGS","Enables Hardware-accelerated GPU scheduling.","Gaming",@"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"" /v HwSchMode /t REG_DWORD /d 2 /f",false,true),
T("21","Disable HAGS","Disables Hardware-accelerated GPU scheduling.","Gaming",@"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"" /v HwSchMode /t REG_DWORD /d 1 /f",false,true),
T("22","Disable mouse acceleration","Disables classic mouse acceleration thresholds.","Input",@"reg add ""HKCU\Control Panel\Mouse"" /v MouseSpeed /t REG_SZ /d 0 /f & reg add ""HKCU\Control Panel\Mouse"" /v MouseThreshold1 /t REG_SZ /d 0 /f & reg add ""HKCU\Control Panel\Mouse"" /v MouseThreshold2 /t REG_SZ /d 0 /f"),
T("23","Keyboard delay 0 / speed 31","Sets the fastest classic keyboard repeat settings.","Input",@"reg add ""HKCU\Control Panel\Keyboard"" /v KeyboardDelay /t REG_SZ /d 0 /f & reg add ""HKCU\Control Panel\Keyboard"" /v KeyboardSpeed /t REG_SZ /d 31 /f"),
T("24","High Performance plan","Activates the Windows High Performance power plan.","Power",@"powercfg /setactive SCHEME_MIN",true),
T("25","Ultimate Performance plan","Attempts to activate the Ultimate Performance power plan.","Power",@"powercfg /duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 >nul 2>&1 & powercfg /setactive e9a42b02-d5df-448d-aa00-03f14749eb61",false),
T("26","Disable power throttling","Disables Windows power throttling.","Power",@"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling"" /v PowerThrottlingOff /t REG_DWORD /d 1 /f",true,true),
T("27","CPU minimum 100% AC","Sets AC processor minimum state to 100%.","Power",@"powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMIN 100 & powercfg /setactive SCHEME_CURRENT"),
T("28","CPU maximum 100% AC","Sets AC processor maximum state to 100%.","Power",@"powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 100 & powercfg /setactive SCHEME_CURRENT"),
T("29","Disable USB selective suspend","Disables USB selective suspend on AC power.","Power",@"powercfg /setacvalueindex SCHEME_CURRENT SUB_USB USBSELECTIVE 0 & powercfg /setactive SCHEME_CURRENT"),
T("30","Disable PCIe ASPM","Disables PCI Express link-state power management on AC power.","Power",@"powercfg /setacvalueindex SCHEME_CURRENT SUB_PCIEXPRESS ASPM 0 & powercfg /setactive SCHEME_CURRENT"),
T("31","MMCSS Games priority","Sets Multimedia Class Scheduler Games task priorities.","Gaming",@"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v ""GPU Priority"" /t REG_DWORD /d 8 /f & reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v Priority /t REG_DWORD /d 6 /f"),
T("32","Network throttling off","Sets NetworkThrottlingIndex to unlimited.","Network",@"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"" /v NetworkThrottlingIndex /t REG_DWORD /d 4294967295 /f"),
T("33","Flush DNS","Flushes the DNS resolver cache.","Network",@"ipconfig /flushdns",false,false,true),
T("34","Reset Winsock","Resets the Winsock catalog; restart may be required.","Network",@"netsh winsock reset",false,true,true),
T("35","Reset TCP/IP","Resets TCP/IP settings; restart may be required.","Network",@"netsh int ip reset",false,true,true),
T("36","Show IP configuration","Displays detailed network configuration.","Diagnostics",@"ipconfig /all",false,false,true),
T("37","Show active power plan","Displays the current active power plan.","Diagnostics",@"powercfg /getactivescheme",false,false,true),
T("38","Component cleanup","Runs DISM component cleanup.","Maintenance",@"DISM /Online /Cleanup-Image /StartComponentCleanup",false,false,true),
T("39","Check Windows system files","Runs System File Checker.","Maintenance",@"sfc /scannow",false,false,true),
T("40","Repair Windows image","Runs DISM RestoreHealth.","Maintenance",@"DISM /Online /Cleanup-Image /RestoreHealth",false,false,true),
T("41","Optimize system drive","Runs Windows drive optimization on C:.","Maintenance",@"defrag C: /O",false,false,true),
T("42","Clear user TEMP","Clears the current user's TEMP contents.","Cleanup",@"del /f /s /q ""%TEMP%\*"" >nul 2>&1 & for /d %%%%D in (""%TEMP%\*"") do rd /s /q ""%%%%D"" >nul 2>&1",false,false,true),
T("43","Clear Windows Update cache","Stops update services, clears Download cache, and starts services again.","Cleanup",@"net stop wuauserv >nul 2>&1 & net stop bits >nul 2>&1 & rd /s /q ""%SystemRoot%\SoftwareDistribution\Download"" >nul 2>&1 & md ""%SystemRoot%\SoftwareDistribution\Download"" >nul 2>&1 & net start bits >nul 2>&1 & net start wuauserv >nul 2>&1",false,true,true),
T("44","Show Windows version","Displays the Windows version.","Diagnostics",@"ver",false,false,true),
T("45","Show system information","Displays Windows system information.","Diagnostics",@"systeminfo",false,false,true),
T("46","Show GPU driver info","Displays GPU names and driver versions.","Diagnostics",@"powershell -NoProfile -Command ""Get-CimInstance Win32_VideoController | Select-Object Name,DriverVersion,DriverDate""",false,false,true),
T("47","SysMain = Manual","Sets SysMain startup to manual.","Services",@"sc config SysMain start= demand"),
T("48","WSearch = Manual","Sets Windows Search startup to manual.","Services",@"sc config WSearch start= demand"),
T("49","MapsBroker = Manual","Sets Downloaded Maps Manager startup to manual.","Services",@"sc config MapsBroker start= demand"),
T("50","Fax = Manual","Sets Fax startup to manual.","Services",@"sc config Fax start= demand"),
T("51","RemoteRegistry = Disabled","Disables Remote Registry service startup.","Services",@"sc config RemoteRegistry start= disabled"),
T("52","RetailDemo = Disabled","Disables Retail Demo service startup.","Services",@"sc config RetailDemo start= disabled"),
T("53","XboxGipSvc = Manual","Sets Xbox Accessory Management service startup to manual.","Services",@"sc config XboxGipSvc start= demand"),
T("54","XblAuthManager = Manual","Sets Xbox Live Auth Manager startup to manual.","Services",@"sc config XblAuthManager start= demand"),
T("55","Disable Delivery Optimization P2P","Disables Delivery Optimization peer downloads.","Privacy",@"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization"" /v DODownloadMode /t REG_DWORD /d 0 /f"),
T("56","Enable long Win32 paths","Enables long path support where applications support it.","Windows",@"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\FileSystem"" /v LongPathsEnabled /t REG_DWORD /d 1 /f",false,true),
T("57","Disable Search device history","Disables device search history setting.","Privacy",@"reg add ""HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings"" /v IsDeviceSearchHistoryEnabled /t REG_DWORD /d 0 /f"),
T("58","Disable Advertising ID","Disables the per-user advertising ID.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo"" /v Enabled /t REG_DWORD /d 0 /f",true),
T("59","Disable background apps","Disables background app access globally where supported.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications"" /v GlobalUserDisabled /t REG_DWORD /d 1 /f",true),
T("60","Disable consumer features","Disables Windows consumer content features.","Privacy",@"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent"" /v DisableWindowsConsumerFeatures /t REG_DWORD /d 1 /f",true,true),
T("61","Disable Edge Startup Boost","Disables Microsoft Edge Startup Boost policy.","Browsers",@"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Edge"" /v StartupBoostEnabled /t REG_DWORD /d 0 /f"),
T("62","Disable Edge Background Mode","Disables Microsoft Edge background mode policy.","Browsers",@"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Edge"" /v BackgroundModeEnabled /t REG_DWORD /d 0 /f"),
T("63","Disable Chrome Startup Boost","Disables Chrome Startup Boost policy.","Browsers",@"reg add ""HKLM\SOFTWARE\Policies\Google\Chrome"" /v StartupBoostEnabled /t REG_DWORD /d 0 /f"),
T("64","Disable Chrome Background Mode","Disables Chrome background mode policy.","Browsers",@"reg add ""HKLM\SOFTWARE\Policies\Google\Chrome"" /v BackgroundModeEnabled /t REG_DWORD /d 0 /f"),
T("65","Disable Remote Assistance","Disables Remote Assistance connections.","Privacy",@"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Remote Assistance"" /v fAllowToGetHelp /t REG_DWORD /d 0 /f",true,true),
T("66","Disable Windows Error Reporting","Disables Windows Error Reporting policies.","Privacy",@"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting"" /v Disabled /t REG_DWORD /d 1 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting"" /v DoReport /t REG_DWORD /d 0 /f"),
T("67","Disable Sticky Keys popup","Disables Sticky Keys accessibility prompt.","Input",@"reg add ""HKCU\Control Panel\Accessibility\StickyKeys"" /v Flags /t REG_SZ /d 506 /f"),
T("68","Disable Toggle Keys popup","Disables Toggle Keys accessibility prompt.","Input",@"reg add ""HKCU\Control Panel\Accessibility\ToggleKeys"" /v Flags /t REG_SZ /d 58 /f"),
T("69","Disable OneDrive setting sync","Disables selected Windows setting sync groups.","Privacy",@"reg add ""HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Personalization"" /v Enabled /t REG_DWORD /d 0 /f & reg add ""HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Windows"" /v Enabled /t REG_DWORD /d 0 /f"),
T("70","Disable app diagnostics consent","Denies app diagnostics capability consent.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics"" /v Value /t REG_SZ /d Deny /f"),
T("71","Disable location consent","Denies user location capability consent.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location"" /v Value /t REG_SZ /d Deny /f"),
T("72","Disable online speech personalization","Disables online speech personalization acceptance.","Privacy",@"reg add ""HKCU\SOFTWARE\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy"" /v HasAccepted /t REG_DWORD /d 0 /f"),
T("73","Disable device metadata downloads","Prevents device metadata downloads from the network.","Privacy",@"reg add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Device Metadata"" /v PreventDeviceMetadataFromNetwork /t REG_DWORD /d 1 /f"),
T("74","Disable silent installed apps","Disables silent consumer app installation.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SilentInstalledAppsEnabled /t REG_DWORD /d 0 /f"),
T("75","Disable content suggestions","Disables Start/content suggestion flags.","Privacy",@"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SystemPaneSuggestionsEnabled /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SoftLandingEnabled /t REG_DWORD /d 0 /f")
    };
}
